apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  replicas: 2
  strategy:
    type: launchingapp
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-app
        image: gurkasathish/wisecow-app:latest
        ports:
        - containerPort: 4499
